version: "3.9"
services:
  api:
    image: python:3.12-slim
    working_dir: /app
    command: bash -lc "pip install -r requirements.txt && uvicorn server:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - alsadika_data:/app/.alsadika
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
  alsadika_data:
