services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    restart: unless-stopped
