name: Android Debug APK
on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/build-android-debug.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install deps & build web
        working-directory: frontend
        run: |
          npm ci --legacy-peer-deps || npm i --legacy-peer-deps
          npm run build
          npx cap sync android

      - name: Build Debug APK
        working-directory: frontend/android
        run: ./gradlew assembleDebug

      - name: Upload app-debug.apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
